# Generated by Django 6.0.4 on 2026-04-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leitorSensor',
            new_name='LeituraSensor',
        ),
    ]
