# Generated by Django 6.0.4 on 2026-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_rename_leitorsensor_leiturasensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventoinha', models.BooleanField(default=False)),
            ],
        ),
    ]
