# Generated by Django 6.0.4 on 2026-04-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='leiturasensor',
            name='umidificador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='ventoinha',
            field=models.BooleanField(default=False),
        ),
    ]
