# Generated by Django 6.0.4 on 2026-04-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_leiturasensor_umidificador_leiturasensor_ventoinha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controle',
        ),
    ]
