# Generated by Django 6.0.4 on 2026-06-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_delete_controle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leiturasensor',
            old_name='temperatura',
            new_name='temperatura_externa',
        ),
        migrations.RenameField(
            model_name='leiturasensor',
            old_name='umidade',
            new_name='temperatura_interna',
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='umidade_externa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='umidade_interna',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
