# Generated by Django 6.0.4 on 2026-07-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0006_rename_temperatura_leiturasensor_temperatura_externa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leiturasensor',
            old_name='temperatura_externa',
            new_name='temperatura',
        ),
        migrations.RenameField(
            model_name='leiturasensor',
            old_name='temperatura_interna',
            new_name='umidade',
        ),
        migrations.RemoveField(
            model_name='leiturasensor',
            name='umidade_externa',
        ),
        migrations.RemoveField(
            model_name='leiturasensor',
            name='umidade_interna',
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='sensor',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10),
            preserve_default=False,
        ),
    ]
