# Generated by Django 6.0.4 on 2026-07-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0007_rename_temperatura_externa_leiturasensor_temperatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leiturasensor',
            name='lampada',
            field=models.BooleanField(default=False),
        ),
    ]
