# Generated by Django 6.0.4 on 2026-07-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0008_leiturasensor_lampada'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuador', models.CharField(max_length=20)),
                ('acao', models.CharField(max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
