# Generated by Django 6.0.4 on 2026-07-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0009_eventoacionamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoacionamento',
            options={'ordering': ['-data']},
        ),
        migrations.RemoveField(
            model_name='eventoacionamento',
            name='acao',
        ),
        migrations.AddField(
            model_name='eventoacionamento',
            name='ligado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventoacionamento',
            name='atuador',
            field=models.CharField(choices=[('Peltier', 'Peltier'), ('Umidificador', 'Umidificador'), ('Lampada', 'Lampada')], max_length=20),
        ),
    ]
